//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractVersionedObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractVersionedObject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.lucidcentral.org/2007/DS/}AbstractObject">
 *       &lt;sequence>
 *         &lt;element name="RevisionData" type="{http://www.lucidcentral.org/2007/DS/}RevisionData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractVersionedObject", propOrder = {
    "revisionData"
})
@XmlSeeAlso({
    FeatureTree.class,
    Entity.class,
    SubsetTree.class,
    EntityTree.class,
    MediaObject.class,
    Feature.class,
    State.class,
    Subset.class,
    Dataset2 .class
})
public class AbstractVersionedObject
    extends AbstractObject
{

    @XmlElement(name = "RevisionData")
    protected RevisionData revisionData;

    /**
     * Gets the value of the revisionData property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionData }
     *     
     */
    public RevisionData getRevisionData() {
        return revisionData;
    }

    /**
     * Sets the value of the revisionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionData }
     *     
     */
    public void setRevisionData(RevisionData value) {
        this.revisionData = value;
    }

}
