//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Audience complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Audience">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.lucidcentral.org/2007/DS/}AbstractObject">
 *       &lt;sequence>
 *         &lt;element name="ExpertiseLevel" type="{http://www.lucidcentral.org/2007/DS/}ExpertiseLevelEnum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Audience", propOrder = {
    "expertiseLevel"
})
public class Audience
    extends AbstractObject
{

    @XmlElement(name = "ExpertiseLevel", required = true)
    protected ExpertiseLevelEnum expertiseLevel;

    /**
     * Gets the value of the expertiseLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ExpertiseLevelEnum }
     *     
     */
    public ExpertiseLevelEnum getExpertiseLevel() {
        return expertiseLevel;
    }

    /**
     * Sets the value of the expertiseLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpertiseLevelEnum }
     *     
     */
    public void setExpertiseLevel(ExpertiseLevelEnum value) {
        this.expertiseLevel = value;
    }

}
