//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Dataset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dataset">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.lucidcentral.org/2007/DS/}AbstractVersionedObject">
 *       &lt;sequence>
 *         &lt;element name="Items" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Entities" type="{http://www.lucidcentral.org/2007/DS/}EntitySet" minOccurs="0"/>
 *                   &lt;element name="Features" type="{http://www.lucidcentral.org/2007/DS/}FeatureSet" minOccurs="0"/>
 *                   &lt;element name="Subsets" type="{http://www.lucidcentral.org/2007/DS/}SubsetSet" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Trees" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="FeatureTrees" type="{http://www.lucidcentral.org/2007/DS/}FeatureTreeSet" minOccurs="0"/>
 *                   &lt;element name="EntityTrees" type="{http://www.lucidcentral.org/2007/DS/}EntityTreeSet" minOccurs="0"/>
 *                   &lt;element name="SubsetTrees" type="{http://www.lucidcentral.org/2007/DS/}SubsetTreeSet" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Descriptions" type="{http://www.lucidcentral.org/2007/DS/}DescriptionSet" minOccurs="0"/>
 *         &lt;element name="Agents" type="{http://www.lucidcentral.org/2007/DS/}AgentSet" minOccurs="0"/>
 *         &lt;element name="MediaObjects" type="{http://www.lucidcentral.org/2007/DS/}MediaObjectSet" minOccurs="0"/>
 *         &lt;element name="Audiences" type="{http://www.lucidcentral.org/2007/DS/}AudienceSet" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="default_lang" type="{http://www.w3.org/2001/XMLSchema}language" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dataset", propOrder = {
    "items",
    "trees",
    "descriptions",
    "agents",
    "mediaObjects",
    "audiences"
})
@XmlSeeAlso({
    Dataset.class
})
public class Dataset2
    extends AbstractVersionedObject
{

    @XmlElement(name = "Items")
    protected Items items;
    @XmlElement(name = "Trees")
    protected Trees trees;
    @XmlElement(name = "Descriptions")
    protected DescriptionSet descriptions;
    @XmlElement(name = "Agents")
    protected AgentSet agents;
    @XmlElement(name = "MediaObjects")
    protected MediaObjectSet mediaObjects;
    @XmlElement(name = "Audiences")
    protected AudienceSet audiences;
    @XmlAttribute(name = "default_lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String defaultLang;

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link org.lucidcentral._2007.ds.Dataset2 .Items }
     *     
     */
    public Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.lucidcentral._2007.ds.Dataset2 .Items }
     *     
     */
    public void setItems(Items value) {
        this.items = value;
    }

    /**
     * Gets the value of the trees property.
     * 
     * @return
     *     possible object is
     *     {@link org.lucidcentral._2007.ds.Dataset2 .Trees }
     *     
     */
    public Trees getTrees() {
        return trees;
    }

    /**
     * Sets the value of the trees property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.lucidcentral._2007.ds.Dataset2 .Trees }
     *     
     */
    public void setTrees(Trees value) {
        this.trees = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionSet }
     *     
     */
    public DescriptionSet getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionSet }
     *     
     */
    public void setDescriptions(DescriptionSet value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the agents property.
     * 
     * @return
     *     possible object is
     *     {@link AgentSet }
     *     
     */
    public AgentSet getAgents() {
        return agents;
    }

    /**
     * Sets the value of the agents property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentSet }
     *     
     */
    public void setAgents(AgentSet value) {
        this.agents = value;
    }

    /**
     * Gets the value of the mediaObjects property.
     * 
     * @return
     *     possible object is
     *     {@link MediaObjectSet }
     *     
     */
    public MediaObjectSet getMediaObjects() {
        return mediaObjects;
    }

    /**
     * Sets the value of the mediaObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaObjectSet }
     *     
     */
    public void setMediaObjects(MediaObjectSet value) {
        this.mediaObjects = value;
    }

    /**
     * Gets the value of the audiences property.
     * 
     * @return
     *     possible object is
     *     {@link AudienceSet }
     *     
     */
    public AudienceSet getAudiences() {
        return audiences;
    }

    /**
     * Sets the value of the audiences property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudienceSet }
     *     
     */
    public void setAudiences(AudienceSet value) {
        this.audiences = value;
    }

    /**
     * Gets the value of the defaultLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLang() {
        return defaultLang;
    }

    /**
     * Sets the value of the defaultLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLang(String value) {
        this.defaultLang = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Entities" type="{http://www.lucidcentral.org/2007/DS/}EntitySet" minOccurs="0"/>
     *         &lt;element name="Features" type="{http://www.lucidcentral.org/2007/DS/}FeatureSet" minOccurs="0"/>
     *         &lt;element name="Subsets" type="{http://www.lucidcentral.org/2007/DS/}SubsetSet" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entities",
        "features",
        "subsets"
    })
    public static class Items {

        @XmlElement(name = "Entities")
        protected EntitySet entities;
        @XmlElement(name = "Features")
        protected FeatureSet features;
        @XmlElement(name = "Subsets")
        protected SubsetSet subsets;

        /**
         * Gets the value of the entities property.
         * 
         * @return
         *     possible object is
         *     {@link EntitySet }
         *     
         */
        public EntitySet getEntities() {
            return entities;
        }

        /**
         * Sets the value of the entities property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntitySet }
         *     
         */
        public void setEntities(EntitySet value) {
            this.entities = value;
        }

        /**
         * Gets the value of the features property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureSet }
         *     
         */
        public FeatureSet getFeatures() {
            return features;
        }

        /**
         * Sets the value of the features property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureSet }
         *     
         */
        public void setFeatures(FeatureSet value) {
            this.features = value;
        }

        /**
         * Gets the value of the subsets property.
         * 
         * @return
         *     possible object is
         *     {@link SubsetSet }
         *     
         */
        public SubsetSet getSubsets() {
            return subsets;
        }

        /**
         * Sets the value of the subsets property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubsetSet }
         *     
         */
        public void setSubsets(SubsetSet value) {
            this.subsets = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="FeatureTrees" type="{http://www.lucidcentral.org/2007/DS/}FeatureTreeSet" minOccurs="0"/>
     *         &lt;element name="EntityTrees" type="{http://www.lucidcentral.org/2007/DS/}EntityTreeSet" minOccurs="0"/>
     *         &lt;element name="SubsetTrees" type="{http://www.lucidcentral.org/2007/DS/}SubsetTreeSet" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "featureTrees",
        "entityTrees",
        "subsetTrees"
    })
    public static class Trees {

        @XmlElement(name = "FeatureTrees")
        protected FeatureTreeSet featureTrees;
        @XmlElement(name = "EntityTrees")
        protected EntityTreeSet entityTrees;
        @XmlElement(name = "SubsetTrees")
        protected SubsetTreeSet subsetTrees;

        /**
         * Gets the value of the featureTrees property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureTreeSet }
         *     
         */
        public FeatureTreeSet getFeatureTrees() {
            return featureTrees;
        }

        /**
         * Sets the value of the featureTrees property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureTreeSet }
         *     
         */
        public void setFeatureTrees(FeatureTreeSet value) {
            this.featureTrees = value;
        }

        /**
         * Gets the value of the entityTrees property.
         * 
         * @return
         *     possible object is
         *     {@link EntityTreeSet }
         *     
         */
        public EntityTreeSet getEntityTrees() {
            return entityTrees;
        }

        /**
         * Sets the value of the entityTrees property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntityTreeSet }
         *     
         */
        public void setEntityTrees(EntityTreeSet value) {
            this.entityTrees = value;
        }

        /**
         * Gets the value of the subsetTrees property.
         * 
         * @return
         *     possible object is
         *     {@link SubsetTreeSet }
         *     
         */
        public SubsetTreeSet getSubsetTrees() {
            return subsetTrees;
        }

        /**
         * Sets the value of the subsetTrees property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubsetTreeSet }
         *     
         */
        public void setSubsetTrees(SubsetTreeSet value) {
            this.subsetTrees = value;
        }

    }

}
