//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Description complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Description">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Data" type="{http://www.lucidcentral.org/2007/DS/}DescriptionData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ref" use="required" type="{http://www.lucidcentral.org/2007/DS/}ShortString" />
 *       &lt;attribute name="debug_label" type="{http://www.lucidcentral.org/2007/DS/}ShortString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Description", propOrder = {
    "data",
    "entity"
})
public class Description {

    @XmlElement(name = "Data")
    protected DescriptionData data;
    @XmlAttribute(name = "ref", required = true)
    protected String ref;
    @XmlAttribute(name = "debug_label")
    protected String debugLabel;

    //add for variation
    @XmlElement(name = "Entity", required = false)
    protected EntityRef entity;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionData }
     *     
     */
    public DescriptionData getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionData }
     *     
     */
    public void setData(DescriptionData value) {
        this.data = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the debugLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebugLabel() {
        return debugLabel;
    }

    /**
     * Sets the value of the debugLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebugLabel(String value) {
        this.debugLabel = value;
    }

    public EntityRef getEntity() {
        return entity;
    }
    public void setEntity(EntityRef entity) {
        this.entity = entity;
    }

}
