//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescriptionText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptionText">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BeforeText" type="{http://www.lucidcentral.org/2007/DS/}LabelText" minOccurs="0"/>
 *         &lt;element name="AfterText" type="{http://www.lucidcentral.org/2007/DS/}LabelText" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ignore" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptionText", propOrder = {
    "beforeText",
    "afterText"
})
public class DescriptionText {

    @XmlElement(name = "BeforeText")
    protected LabelText beforeText;
    @XmlElement(name = "AfterText")
    protected LabelText afterText;
    @XmlAttribute(name = "ignore")
    protected Boolean ignore;

    /**
     * Gets the value of the beforeText property.
     * 
     * @return
     *     possible object is
     *     {@link LabelText }
     *     
     */
    public LabelText getBeforeText() {
        return beforeText;
    }

    /**
     * Sets the value of the beforeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelText }
     *     
     */
    public void setBeforeText(LabelText value) {
        this.beforeText = value;
    }

    /**
     * Gets the value of the afterText property.
     * 
     * @return
     *     possible object is
     *     {@link LabelText }
     *     
     */
    public LabelText getAfterText() {
        return afterText;
    }

    /**
     * Sets the value of the afterText property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelText }
     *     
     */
    public void setAfterText(LabelText value) {
        this.afterText = value;
    }

    /**
     * Gets the value of the ignore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIgnore() {
        return ignore;
    }

    /**
     * Sets the value of the ignore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIgnore(Boolean value) {
        this.ignore = value;
    }

}
