//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetailText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetailText">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.lucidcentral.org/2007/DS/>LongStringText">
 *       &lt;attribute name="role" type="{http://www.lucidcentral.org/2007/DS/}DetailRoleEnum" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetailText")
public class DetailText
    extends LongStringText
{

    @XmlAttribute(name = "role")
    protected DetailRoleEnum role;

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link DetailRoleEnum }
     *     
     */
    public DetailRoleEnum getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailRoleEnum }
     *     
     */
    public void setRole(DetailRoleEnum value) {
        this.role = value;
    }

}
