//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureTreeNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureTreeNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Parent" type="{http://www.lucidcentral.org/2007/DS/}FeatureTreeNodeRef" minOccurs="0"/>
 *         &lt;element name="DependencyRules" type="{http://www.lucidcentral.org/2007/DS/}DependencyRules" minOccurs="0"/>
 *         &lt;element name="Representation" type="{http://www.lucidcentral.org/2007/DS/}Representation" minOccurs="0"/>
 *         &lt;element name="Feature" type="{http://www.lucidcentral.org/2007/DS/}FeatureRef" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.lucidcentral.org/2007/DS/}ShortString" />
 *       &lt;attribute name="debug_label" type="{http://www.lucidcentral.org/2007/DS/}ShortString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureTreeNode", propOrder = {
    "parent",
    "dependencyRules",
    "representation",
    "feature"
})
public class FeatureTreeNode {

    @XmlElement(name = "Parent")
    protected FeatureTreeNodeRef parent;
    @XmlElement(name = "DependencyRules")
    protected DependencyRules dependencyRules;
    @XmlElement(name = "Representation")
    protected Representation representation;
    @XmlElement(name = "Feature")
    protected FeatureRef feature;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "debug_label")
    protected String debugLabel;

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureTreeNodeRef }
     *     
     */
    public FeatureTreeNodeRef getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureTreeNodeRef }
     *     
     */
    public void setParent(FeatureTreeNodeRef value) {
        this.parent = value;
    }

    /**
     * Gets the value of the dependencyRules property.
     * 
     * @return
     *     possible object is
     *     {@link DependencyRules }
     *     
     */
    public DependencyRules getDependencyRules() {
        return dependencyRules;
    }

    /**
     * Sets the value of the dependencyRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencyRules }
     *     
     */
    public void setDependencyRules(DependencyRules value) {
        this.dependencyRules = value;
    }

    /**
     * Gets the value of the representation property.
     * 
     * @return
     *     possible object is
     *     {@link Representation }
     *     
     */
    public Representation getRepresentation() {
        return representation;
    }

    /**
     * Sets the value of the representation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Representation }
     *     
     */
    public void setRepresentation(Representation value) {
        this.representation = value;
    }

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureRef }
     *     
     */
    public FeatureRef getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureRef }
     *     
     */
    public void setFeature(FeatureRef value) {
        this.feature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the debugLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebugLabel() {
        return debugLabel;
    }

    /**
     * Sets the value of the debugLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebugLabel(String value) {
        this.debugLabel = value;
    }

}
