//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementUnitPrefixEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasurementUnitPrefixEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="deci"/>
 *     &lt;enumeration value="centi"/>
 *     &lt;enumeration value="milli"/>
 *     &lt;enumeration value="micro"/>
 *     &lt;enumeration value="deca"/>
 *     &lt;enumeration value="hecto"/>
 *     &lt;enumeration value="kilo"/>
 *     &lt;enumeration value="mega"/>
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MeasurementUnitPrefixEnum")
@XmlEnum
public enum MeasurementUnitPrefixEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("deci")
    DECI("deci"),
    @XmlEnumValue("centi")
    CENTI("centi"),
    @XmlEnumValue("milli")
    MILLI("milli"),
    @XmlEnumValue("micro")
    MICRO("micro"),
    @XmlEnumValue("deca")
    DECA("deca"),
    @XmlEnumValue("hecto")
    HECTO("hecto"),
    @XmlEnumValue("kilo")
    KILO("kilo"),
    @XmlEnumValue("mega")
    MEGA("mega"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    MeasurementUnitPrefixEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MeasurementUnitPrefixEnum fromValue(String v) {
        for (MeasurementUnitPrefixEnum c: MeasurementUnitPrefixEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
