//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementUnitEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MeasurementUnitEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="metre"/>
 *     &lt;enumeration value="square_metre"/>
 *     &lt;enumeration value="cubic_metre"/>
 *     &lt;enumeration value="litre"/>
 *     &lt;enumeration value="degrees_celcius"/>
 *     &lt;enumeration value="degrees_planar"/>
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MeasurementUnitEnum")
@XmlEnum
public enum MeasurementUnitEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("metre")
    METRE("metre"),
    @XmlEnumValue("square_metre")
    SQUARE_METRE("square_metre"),
    @XmlEnumValue("cubic_metre")
    CUBIC_METRE("cubic_metre"),
    @XmlEnumValue("litre")
    LITRE("litre"),
    @XmlEnumValue("degrees_celcius")
    DEGREES_CELCIUS("degrees_celcius"),
    @XmlEnumValue("degrees_planar")
    DEGREES_PLANAR("degrees_planar"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    MeasurementUnitEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MeasurementUnitEnum fromValue(String v) {
        for (MeasurementUnitEnum c: MeasurementUnitEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
