//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.13 at 10:31:49 AM EST 
//


package org.lucidcentral._2007.ds;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.lucidcentral._2007.ds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.lucidcentral._2007.ds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dataset2 }
     * 
     */
    public Dataset2 createDataset2() {
        return new Dataset2();
    }

    /**
     * Create an instance of {@link NumericDataValue }
     * 
     */
    public NumericDataValue createNumericDataValue() {
        return new NumericDataValue();
    }

    /**
     * Create an instance of {@link Dataset }
     * 
     */
    public Dataset createDataset() {
        return new Dataset();
    }

    /**
     * Create an instance of {@link AbstractVersionedObject }
     * 
     */
    public AbstractVersionedObject createAbstractVersionedObject() {
        return new AbstractVersionedObject();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link LinkSet }
     * 
     */
    public LinkSet createLinkSet() {
        return new LinkSet();
    }

    /**
     * Create an instance of {@link RevisionData }
     * 
     */
    public RevisionData createRevisionData() {
        return new RevisionData();
    }

    /**
     * Create an instance of {@link Dataset2 .Items }
     * 
     */
    public Dataset2 .Items createDataset2Items() {
        return new Dataset2 .Items();
    }

    /**
     * Create an instance of {@link Dataset2 .Trees }
     * 
     */
    public Dataset2 .Trees createDataset2Trees() {
        return new Dataset2 .Trees();
    }

    /**
     * Create an instance of {@link DescriptionSet }
     * 
     */
    public DescriptionSet createDescriptionSet() {
        return new DescriptionSet();
    }

    /**
     * Create an instance of {@link AgentSet }
     * 
     */
    public AgentSet createAgentSet() {
        return new AgentSet();
    }

    /**
     * Create an instance of {@link MediaObjectSet }
     * 
     */
    public MediaObjectSet createMediaObjectSet() {
        return new MediaObjectSet();
    }

    /**
     * Create an instance of {@link AudienceSet }
     * 
     */
    public AudienceSet createAudienceSet() {
        return new AudienceSet();
    }

    /**
     * Create an instance of {@link LabelText }
     * 
     */
    public LabelText createLabelText() {
        return new LabelText();
    }

    /**
     * Create an instance of {@link DetailText }
     * 
     */
    public DetailText createDetailText() {
        return new DetailText();
    }

    /**
     * Create an instance of {@link SubsetTreeNodeSet }
     * 
     */
    public SubsetTreeNodeSet createSubsetTreeNodeSet() {
        return new SubsetTreeNodeSet();
    }

    /**
     * Create an instance of {@link SubsetTreeNodeRef }
     * 
     */
    public SubsetTreeNodeRef createSubsetTreeNodeRef() {
        return new SubsetTreeNodeRef();
    }

    /**
     * Create an instance of {@link DescriptionText }
     * 
     */
    public DescriptionText createDescriptionText() {
        return new DescriptionText();
    }

    /**
     * Create an instance of {@link Modifier }
     * 
     */
    public Modifier createModifier() {
        return new Modifier();
    }

    /**
     * Create an instance of {@link NumericDataValueSet }
     * 
     */
    public NumericDataValueSet createNumericDataValueSet() {
        return new NumericDataValueSet();
    }

    /**
     * Create an instance of {@link EntityTreeSet }
     * 
     */
    public EntityTreeSet createEntityTreeSet() {
        return new EntityTreeSet();
    }

    /**
     * Create an instance of {@link FeatureTreeSet }
     * 
     */
    public FeatureTreeSet createFeatureTreeSet() {
        return new FeatureTreeSet();
    }

    /**
     * Create an instance of {@link SubsetRef }
     * 
     */
    public SubsetRef createSubsetRef() {
        return new SubsetRef();
    }

    /**
     * Create an instance of {@link SubsetTreeSet }
     * 
     */
    public SubsetTreeSet createSubsetTreeSet() {
        return new SubsetTreeSet();
    }

    /**
     * Create an instance of {@link SubsetTreeNode }
     * 
     */
    public SubsetTreeNode createSubsetTreeNode() {
        return new SubsetTreeNode();
    }

    /**
     * Create an instance of {@link SubsetSet }
     * 
     */
    public SubsetSet createSubsetSet() {
        return new SubsetSet();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link MediaObjectRef }
     * 
     */
    public MediaObjectRef createMediaObjectRef() {
        return new MediaObjectRef();
    }

    /**
     * Create an instance of {@link NumericMeasure }
     * 
     */
    public NumericMeasure createNumericMeasure() {
        return new NumericMeasure();
    }

    /**
     * Create an instance of {@link MeasurementUnit }
     * 
     */
    public MeasurementUnit createMeasurementUnit() {
        return new MeasurementUnit();
    }

    /**
     * Create an instance of {@link StateData }
     * 
     */
    public StateData createStateData() {
        return new StateData();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link FeatureTreeNodeSet }
     * 
     */
    public FeatureTreeNodeSet createFeatureTreeNodeSet() {
        return new FeatureTreeNodeSet();
    }

    /**
     * Create an instance of {@link EntityTreeNode }
     * 
     */
    public EntityTreeNode createEntityTreeNode() {
        return new EntityTreeNode();
    }

    /**
     * Create an instance of {@link FeatureTree }
     * 
     */
    public FeatureTree createFeatureTree() {
        return new FeatureTree();
    }

    /**
     * Create an instance of {@link FeatureTreeNode }
     * 
     */
    public FeatureTreeNode createFeatureTreeNode() {
        return new FeatureTreeNode();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link FeatureTreeNodeRef }
     * 
     */
    public FeatureTreeNodeRef createFeatureTreeNodeRef() {
        return new FeatureTreeNodeRef();
    }

    /**
     * Create an instance of {@link SubsetTree }
     * 
     */
    public SubsetTree createSubsetTree() {
        return new SubsetTree();
    }

    /**
     * Create an instance of {@link StateRefSet }
     * 
     */
    public StateRefSet createStateRefSet() {
        return new StateRefSet();
    }

    /**
     * Create an instance of {@link MultistateData }
     * 
     */
    public MultistateData createMultistateData() {
        return new MultistateData();
    }

    /**
     * Create an instance of {@link AgentRef }
     * 
     */
    public AgentRef createAgentRef() {
        return new AgentRef();
    }

    /**
     * Create an instance of {@link StateRef }
     * 
     */
    public StateRef createStateRef() {
        return new StateRef();
    }

    /**
     * Create an instance of {@link EntityTree }
     * 
     */
    public EntityTree createEntityTree() {
        return new EntityTree();
    }

    /**
     * Create an instance of {@link MediaObject }
     * 
     */
    public MediaObject createMediaObject() {
        return new MediaObject();
    }

    /**
     * Create an instance of {@link DependencyRules }
     * 
     */
    public DependencyRules createDependencyRules() {
        return new DependencyRules();
    }

    /**
     * Create an instance of {@link StateSet }
     * 
     */
    public StateSet createStateSet() {
        return new StateSet();
    }

    /**
     * Create an instance of {@link Audience }
     * 
     */
    public Audience createAudience() {
        return new Audience();
    }

    /**
     * Create an instance of {@link NumericFeature }
     * 
     */
    public NumericFeature createNumericFeature() {
        return new NumericFeature();
    }

    /**
     * Create an instance of {@link FeatureRef }
     * 
     */
    public FeatureRef createFeatureRef() {
        return new FeatureRef();
    }

    /**
     * Create an instance of {@link EntityRef }
     * 
     */
    public EntityRef createEntityRef() {
        return new EntityRef();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link EntityTreeNodeSet }
     * 
     */
    public EntityTreeNodeSet createEntityTreeNodeSet() {
        return new EntityTreeNodeSet();
    }

    /**
     * Create an instance of {@link MediaObjectSource }
     * 
     */
    public MediaObjectSource createMediaObjectSource() {
        return new MediaObjectSource();
    }

    /**
     * Create an instance of {@link MultistateFeature }
     * 
     */
    public MultistateFeature createMultistateFeature() {
        return new MultistateFeature();
    }

    /**
     * Create an instance of {@link EntitySet }
     * 
     */
    public EntitySet createEntitySet() {
        return new EntitySet();
    }

    /**
     * Create an instance of {@link DescriptionData }
     * 
     */
    public DescriptionData createDescriptionData() {
        return new DescriptionData();
    }

    /**
     * Create an instance of {@link EntityTreeNodeRef }
     * 
     */
    public EntityTreeNodeRef createEntityTreeNodeRef() {
        return new EntityTreeNodeRef();
    }

    /**
     * Create an instance of {@link UnitPrefix }
     * 
     */
    public UnitPrefix createUnitPrefix() {
        return new UnitPrefix();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link AgentRefSet }
     * 
     */
    public AgentRefSet createAgentRefSet() {
        return new AgentRefSet();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link NumericData }
     * 
     */
    public NumericData createNumericData() {
        return new NumericData();
    }

    /**
     * Create an instance of {@link FeatureSet }
     * 
     */
    public FeatureSet createFeatureSet() {
        return new FeatureSet();
    }

    /**
     * Create an instance of {@link Subset }
     * 
     */
    public Subset createSubset() {
        return new Subset();
    }

    /**
     * Create an instance of {@link NumericDataValue.Measure }
     * 
     */
    public NumericDataValue.Measure createNumericDataValueMeasure() {
        return new NumericDataValue.Measure();
    }

}
