language: groovy
sudo: false
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- export TZ=Australia/Canberra
- date
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION:$GRAILS_VERSION"
- gvm install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy";
  fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
- MAVEN_REPO="ala-repo-snapshot"
- grep '^\s*app\.version=' ./application.properties | grep -q "\-SNAPSHOT"; if [ "$?"
  = "1" ]; then MAVEN_REPO="ala-repo-release"; fi;
- echo "MAVEN_REPO:$MAVEN_REPO"
script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive && grails prod maven-install --non-interactive
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grails prod maven-deploy
  --repository=$MAVEN_REPO --non-interactive'
env:
  global:
  - secure: YJeOKz3ATOSwqkLzse+leNSq2dhuOEWy5wL71/sJfEE/LAqQ5rV/zQL8fvqFLVxZCU/sFTJEXqjeyoY+Ez4h7KXEH6WvqVN8HuYv4dESFbb7rhjPAJjwOlvoVG8ga4X144rUKztc8kOSo6DtfTk3e3crqY9mxWA0XqcI9fz8YXk=
  - secure: FINQrOHOd2a+uP7wD1D2XMJ5ECoIUKQymttyWr9efxu/G0H4HuzVbds5cyrrvwIq51smzGDEp9JEikHg9/90ItnM+zOKrhB8Cors9yui/Pto7rOZAaY9AiAmdvw2dJl/vhcuY2Dc1Ys2DNlsLg++iFiyKJr0Ssc7gsQ70homNBc=
